# Generated by Django 5.2.7 on 2025-10-09 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='departamento',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='forma_pago',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='roles',
            old_name='descripcion',
            new_name='description',
        ),
    ]
