# Generated by Django 5.2.8 on 2025-11-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_descripcion_cargo_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=200)),
                ('supervisor', models.CharField(max_length=100)),
                ('notas', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Zona de Trabajo',
                'verbose_name_plural': 'Zonas de Trabajo',
                'db_table': 'zona_trabajo',
                'managed': True,
            },
        ),
    ]
